# Default values for zats-letschat-mongodb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: sinenomine/mongodb-s390x
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: mongo
  tier: backend
  modifiedBy: SebLL
  useHardwareCryptography: yes
  type: ClusterIP
  protocol: TCP
  externalPort: 27017
  internalPort: 27017
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 128Mi
